version: '3.4'

services:
  theonlyparty.discordbot:
    image: ${DOCKER_REGISTRY-}theonlypartydiscordbot
    build:
      context: .
      dockerfile: TheOnlyParty.DiscordBot/Dockerfile
    environment:
      - AppSettings__DiscordToken
      - AppSettings__DiscordStatus=Watching for Josh's antics
      - AppSettings__DiscordDebugGuildId
      - AppSettings__LoggingUri=http://seq
      - AppSettings__LoggingKey
      - AppSettings__ReplUri=http://repl:31337
      - AppSettings__MlUri=http://mlmodel1_webapi1:8050
    depends_on:
      - seq
      - repl
      - mlmodel1_webapi1

  seq:
    image: datalust/seq:2021.3.6681
    ports:
        - 8090:80
    environment:
        - ACCEPT_EULA=Y
    volumes:
        - seqdata:/data

  repl:
    image: ghcr.io/discord-csharp/csharprepl:latest
    restart: always
    read_only: true
    user: www-data
    environment: 
      - ASPNETCORE_URLS=http://+:31337
    ports:
      - '31337:31337'
    tmpfs:
      - /tmp
      - /var

  mlmodel1_webapi1:
    image: ${DOCKER_REGISTRY-}mlmodel1webapi1
    build:
      context: .
      dockerfile: MLModel1_WebApi1/Dockerfile
    ports:
      - 8050:80

volumes:
  seqdata:
