version: '3.4'

services:
  theonlyparty.discordbot:
    image: ${DOCKER_REGISTRY-}theonlypartydiscordbot
    build:
      context: .
      dockerfile: TheOnlyParty.DiscordBot/Dockerfile
    environment:
      - AppSettings__DiscordToken
      - AppSettings__DiscordStatus=Testing in progress!
      - AppSettings__DiscordDebugGuildId
      - AppSettings__LoggingUri=http://seq
      - AppSettings__LoggingKey
      - AppSettings__ReplUri=http://repl:31337
      - AppSettings__MlUri=http://mlmodel1webapi1
    depends_on:
      - seq
      - repl
      - mlmodel1webapi1
    networks:
      - backend

  seq:
    image: datalust/seq:2021.3.6681
    ports:
        - 31335:80
    environment:
        - ACCEPT_EULA=Y
    volumes:
        - seqdata:/data
    networks:
      - backend

  repl:
    image: ghcr.io/discord-csharp/csharprepl:latest
    restart: always
    read_only: true
    user: www-data
    environment: 
      - ASPNETCORE_URLS=http://+:31337
    ports:
      - '31337:31337'
    tmpfs:
      - /tmp
      - /var
    networks:
      - backend

  mlmodel1webapi1:
    image: ${DOCKER_REGISTRY-}mlmodel1webapi1
    build:
      context: .
      dockerfile: MLModel1_WebApi1/Dockerfile
    ports:
      - 31330:80
    networks:
      - backend

volumes:
  seqdata:

networks:
  backend: