version: '3.4'

services:
  workerservice:
    image: nickmartin1ee7/theonlypartydiscordbot:latest
    environment:
      - AppSettings__DiscordToken
      - AppSettings__DiscordStatus
      - AppSettings__DiscordDebugGuildId
      - AppSettings__LoggingUri
      - AppSettings__LoggingKey
      - AppSettings__ReplUri
      - AppSettings__MlUri
    depends_on:
      - seq
      - repl
      - mlwebapi
    volumes:
      - discorddata:/app/Data
    deploy:
      replicas: 1
      mode: replicated
      update_config:
        parallelism: 1
      restart_policy:
        condition: any
        delay: 5s

  seq:
    image: datalust/seq:2021.3.6681
    ports:
        - 8090:80
    environment:
        - ACCEPT_EULA=Y
    volumes:
        - seqdata:/data
    deploy:
      replicas: 1
      mode: replicated
      update_config:
        parallelism: 1
      restart_policy:
        condition: any

  mlwebapi:
    image: nickmartin1ee7/mlwebapi:latest
    ports:
      - 8091:80
    deploy:
      replicas: 2
      mode: replicated
      update_config:
        parallelism: 1
      restart_policy:
        condition: any

  repl:
    image: ghcr.io/discord-csharp/csharprepl:latest
    restart: always
    read_only: true
    user: www-data
    environment: 
      - ASPNETCORE_URLS=http://+:31337
    ports:
      - '8092:31337'
    volumes:
      - repl-tmp:/tmp
      - repl-var:/var
    deploy:
      replicas: 3
      mode: replicated
      update_config:
        parallelism: 2
        delay: 0s
        order: start-first
      restart_policy:
        condition: any
        delay: 0s
      placement:
        constraints:
          - "node.role==manager"

volumes:
  seqdata:
  discorddata:
  repl-tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
  repl-var:
    driver_opts:
      type: tmpfs
      device: tmpfs
